### ISSUE TITLE
Not compiling with Kotlin 1.3.0

### ISSUE THREAD

**Issue by hardysim** [lisawray/groupie#218]
I've just updated my project (which is using groupie 2.1.0) to Kotlin 1.3.0 and cannot compile anymore. It seems like every use of `GroupAdapter` is failing now:

> error: cannot find symbol
    private final MyFragment$groupAdapter$2$1 getGroupAdapter()

**Comment by bernaferrari** [comment]
Weird.. I updated some projects yesterday to Kotlin 1.3.0 and had no issue with anything.

**Comment by fawaad** [comment]
I'm seeing the same thing as @hardysim. Every instance of `GroupAdapter`, `ViewHolder`, or `Section` (the only I've seen thus far) can not be found.

**Comment by bernaferrari** [comment]
Did you try invalidating the cache + restarting + clean build?

**Comment by hardysim** [comment]
> Did you try invalidating the cache + restarting + clean build?

Yes, tried everything, but no luck 😢 

- updated kotlin-plugin to 1.3.0
- set kotlin-version in gradle to 1.3.0
- tried restart / invalidate + restart
- clean project multiple times
- even tried out groupie 2.1.0-alpha1

**Comment by hardysim** [comment]
Maybe I need to clarify that I'm using kotlin and the error is on the generated java-file for it.
When looking at the kotlin-file all references are working.

Plus, it seems that the exact point of the error is the kotlin-property (which is translated to a getter in java):

```kotlin
private val groupAdapter = GroupAdapter<ViewHolder>()
```

Which results in

> error: cannot find symbol
private final MyFragment$groupAdapter$2$1 getGroupAdapter()

> symbol:   class MyFragment$groupAdapter$2$1
  location: package my.package

When using a function-local `val` it works but as soon as I put the adapter in a property I get this error.

**Comment by hardysim** [comment]
Further investigation: It looks like it's working when using a "plain" instance of `GroupAdapter` like so:

```kotlin
private val groupAdapter by lazy { GroupAdapter<ViewHolder>() }
```

but not when using an `object` (I need this to add a custom interface to the adapter)

```kotlin
private val groupAdapter by lazy { object : GroupAdapter<ViewHolder>() { [...] } }
```

**Comment by hardysim** [comment]
Ok, last post until you guys have an idea (it's working even with `object` in a demo-project I've just created).

I have a workaround:

Since it occurs *only when using an `object` **and** `by lazy`*  I was able to get it working by *using a custom-getter on the property* (instead of lazy-loading it):

```kotlin
private val groupAdapter
        get() = object : GroupAdapter<ViewHolder>() { [...] }
```

I need to delay the creation because I use the fragment's `context` in the object-body (I've added a custom interface to the adapter).

---

That's not perfect, but it works for me (hopefully).
What about you, @fawaad - can you use my workaround?

**Comment by hardysim** [comment]
Well, compiling does not mean working. Using a property results in empty lists 😢 

But it seems that you can use a function to create the adapter and call this function in the `by lazy` of the property. Basically move the stuff from the lambda into an "actual" function.

```kotlin
private fun createGroupAdapter(): GroupAdapter<ViewHolder> {
    return object : GroupAdapter<ViewHolder>() { [...] }
}

private val groupAdapter by lazy { createGroupAdapter() }
```

**Comment by bernaferrari** [comment]
https://github.com/bernaferrari/ChangeDetection

https://github.com/bernaferrari/SDKMonitor

So weird. Could you try any of my projects? Both are working perfectly for me.

**Comment by fawaad** [comment]
Sorry folks, none of those options ended up working for me. I have to put the triaging on hold for the moment though. If it is any help, I also and using AndroidX which isn't fully supported by Groupie.

**Comment by lisawray** [comment]
Hey @fawaad.  Can you give this a try with 2.2.0?

**Comment by hardysim** [comment]
Not working with 2.2 or 2.3 (that's a release cycle 😄).
But I now think it's a Kotlin 1.3 problem and **has nothing to do with groupie**.

I've created a small example which is *not working in my project* but *working fine in any other*:

```kotlin
open class Foo

class Bar {
    private val foo by lazy {
        object : Foo() {}
    }
}
```

As soon as I combine `object` and `by lazy` it cannot compile anymore and shows the "cannot find symbol" error. Using each one alone works.

But this happens only on my project and not in any newly created so maybe it's a conflicting dependency or something.

---

Does anyone has an idea for this (keeping groupie aside)?

I've created a SO question here: https://stackoverflow.com/q/53168385/2170109

**Comment by hardysim** [comment]
Ah, here we go: It's the `experimental`-flag in gradle!

```
androidExtensions {
    experimental = true
}
```

When setting this in my demo-project (where `by lazy` and `object` is working) it starts showing the same error.

But we need this flag *to enable view caching in viewholders*.
@lisawray is this still needed?

**Comment by hardysim** [comment]
More info: It seems that enabling the `experimental`-flag **does not trigger this error**.

But, I can reproduce it in a demo-project (blank "new project" from Android Studio) where I've added more and more dependencies from my actual project to see what is causing this error.

See https://github.com/hardysim/bylazy-demo

---

Turns out, I'm using the gradle-plugins `kotlin-kapt` and `realm-android` and these two **combined** cause this.

Can you please checkout the demo-project and verify it? It should *not compile* in the current state and starts working when you remove either `kotlin-kapt` or `realm-android`.

And when we can verify that this is the cause we can:
- close this issue
- help me to get it fixed 😉

**Comment by fawaad** [comment]
Thanks for updating this @lisawray. This has fixed my compiling issues!

**Comment by lisawray** [comment]
Awesome @fawaad . 

@hardysim , if you're seeing this issue in a project that doesn't include groupie at all, I'm gonna go ahead and say it's not our bug.  I can't tell you the trouble I went through with `kapt` and `realm-android` in the early days 🙄 On the flip side, I've always found them to be really responsive ... so I'd raise a bug with Realm!

**Comment by hardysim** [comment]
For anyone getting here in the future, I'll leave some crosslinks:

- https://github.com/realm/realm-java/issues/6289
- https://stackoverflow.com/questions/53168385/

**Comment by psteiger** [comment]
+1 I've been having intermitent problems like this since Kotlin 1.2 ans this keeps happening in 1.3. I don't use Groupie.

**Comment by GAumala** [comment]
I'm also having this issue when mixing `object` and `lazy`. These are the only plugins I use:

``` groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
```

My kotlin code: 
``` kotlin
class SetupService: Service() {

    private val defaultJob = Job()
    private val defaultScope = CoroutineScope(defaultJob + Dispatchers.Main)
    private val binder by lazy { SetupBinder(SharedPrefsStorage(this)) }
    private val reporter by lazy {
        object : ProgressReporter() {
            override fun onProgressChanged(progress: Int) {
                val setupProgress = SetupProgress.Populating(progress)
                binder.publishProgress(setupProgress)
            }

        }
    }
    private var isRunning = false
}
```

Error message:

```
error: cannot find symbol
    private final com.gaumala.xxxxx.backend.setup.SetupService$reporter$2$1 getReporter() {
                                                 ^
  symbol:   class SetupService$reporter$2$1
  location: package com.gaumala.xxxxx.backend.setup
```

I can confirm that @hardysim 's workaround of replacing lazy with a custom getter works.

**Comment by hardysim** [comment]
@GAumala have you seen my fix here? https://github.com/realm/realm-java/issues/6289#issuecomment-436617795

This is based on the comment here: https://youtrack.jetbrains.net/issue/KT-28053#focus=streamItem-27-3143457-0-0

**Comment by GAumala** [comment]
@hardysim That works better. Thank you!
